name: CreditCard_DNN
n_gpu: 1

data_loader:
  type: CreditCardDataLoader
  args:
    data_dir: ../Data/hw2/
    filename: creditcard_small.csv
    batch_size: 1024
    shuffle: true
    validation_split: 0.2
    num_workers: 4

arch:
  type: DNN
  args:
    num_features: 28
    num_classes: 2

optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true

loss: nll_loss

metrics:
  - accuracy
  - precision
  - recall
  - f1_score

plots:
  - confusion_matrix
  - roc_curve
  - precision_recall_curve
  - lift_curve

trainer:
  epochs: 50
  save_dir: ../Checkpoint/hw2/
  save_period: 1
  log_step: 10
  verbosity: 2
  monitor: min val_loss
  early_stop: 10
  tensorboard: True
