name: Fashion_Mnist_CNN
n_gpu: 1

arch:
  type: CNN_Simple
  args:
    num_classes: 10
    drop_prob: 0.2

data_loader:
  type: FashionMnistDataLoader
  args:
    data_dir: ../Data/hw3/
    batch_size: 128
    shuffle: true
    validation_split: 0.2
    num_workers: 8
    transform_args:
      ToTensor: {}

optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true

loss: nll_loss

metrics:
  - accuracy

plots: {}

lr_scheduler:
  type: StepLR
  args:
    step_size: 50
    gamma: 0.1

trainer:
  epochs: 50
  save_dir: ../Checkpoint/hw3/
  save_period: 1
  log_step: 10
  verbosity: 2
  monitor: min val_loss
  early_stop: 10
  tensorboard: true
