name: Finance_GRU
n_gpu: 1

arch:
  type: GRU
  args:
    embedding_dim: 10
    hidden_dim: 64
    seq_len: 30

data_loader:
  type: FinanceDataLoader
  args:
    data_dir: ../Data/hw4/
    batch_size: 128
    shuffle: true
    validation_split: 0.0
    num_workers: 4
    pin_memory: true

optimizer:
  type: Adam
  args:
    lr: 0.0001
    weight_decay: 0
    amsgrad: true

loss: mse_loss

metrics:
  - mean_square_error

plots:
  - predict_curve

lr_scheduler:
  type: StepLR
  args:
    step_size: 50
    gamma: 0.1

trainer:
  epochs: 50
  save_dir: ../Checkpoint/hw4/
  save_period: 1
  log_step: 10
  verbosity: 2
  monitor: min val_loss
  early_stop: 50
  tensorboard: true

tester:
  verbosity: 2
